name: website_deployment_workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout website code
        uses: actions/checkout@v5
      - name: setup nodjs
        uses: actions/setup-node@v6
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci # in dbt this would br dbt deps
      - name: run tests
        run: npm test
      - name: deploy
        run: echo " Code is being deployed"
  deploy:
    runs-on: ubuntu-latest # setting up the runner
    needs: [test]
    steps:
      - name: checkout website code
        uses: actions/checkout@v5
      - name: setup nodjs
        uses: actions/setup-node@v6
        with:
          Node-version: 18
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm build
